
apiVersion: v1
kind: Pod
metadata: 
  name: mypod3
  namespace: mynamespacesemployee
  labels:
    app: newappemployee
spec: 
  containers: 
    - name: employee
      image: fazilasayyed/employee
      ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: employeeservice
  namespace: mynamespacesemployee
spec:
  type: LoadBalancer
  selector:
    app: newappemployee
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: employee
